### PR TITLE
Add ability to AJAX submit CartForm

### PR DESCRIPTION
**Pull request by adrian-stein**
This allows the extension of the CartForm to work with AJAX submission. The only issue is it will not work come version 2.0 due to https://github.com/burnbright/silverstripe-shop/commit/e04eb1f5498d90630b7282b11d2e68507341ea1a How did you want to proceed. I will fix and then squash all commits to together.

### CODE REVIEW

**Comment by markguinn** [comment]
Actually this should continue to work just fine because the extension is applied to CartPage_Controller. The only thing that's deprecated is putting the extension on CartPage - which will continue to work until 2.0 and then be removed.

**Comment by bummzack** [comment]
This might not be the right place to ask, but I'm wondering where the `updateCartFormResponse` hook is being called? It seems this would be necessary in order to make the `CartForm` work with AJAX submissions, but I can't find any calls to it.

**Comment by markguinn** [comment]
I think you're right, @bummzack. @adrian-stein were you going to submit a PR for that change as well?

**Comment by adrian-stein** [comment]
Nice catch @bummzack I thought I had. I guess not. it is now done https://github.com/burnbright/silverstripe-shop/pull/395/files

**Pull request merged**
