### PR TITLE
Adds optional choice to show message when submitting via AJAX

### PR DESCRIPTION
**Pull request by adrian-stein**
Added a triggered event that shows a message depending on the cart action is. I added the flag so people using the module wont suddenly get notifications appearing when they were not before.

### CODE REVIEW

**Comment by markguinn** [comment]
Yeah, I think this makes sense. Besides converting spaces to tabs there are a couple things I'd love to see changed if you don't mind. First, I think the config setting needs to be true by default and second I think it should be on ShoppingCartAjax instead of ShoppingCart_Controller. Does that make sense? Thanks again for testing this out and for your contribution!

**Comment by adrian-stein** [comment]
Yeah I can move it to ShoppingCartAjax, we would just have to set up a config for it. I put it on ShoppingCart_Controller. as there was already a config there to assign it to it. I think it should be true by default as well but didn't do it encase people pulled in the new version and then the messages started showing. Thoughts?

**Comment by markguinn** [comment]
Ah, I see. For some reason I was thinking that the messages were already there. My bad. In that case lets leave it to false by default.

**Comment by adrian-stein** [comment]
Moved show_ajax_messages to ShoppingCartAjax. All ready to go now.

**Comment by markguinn** [comment]
Great. Have you tested this locally to verify that the config setting gets picked up?

**Comment by adrian-stein** [comment]
Yup. I sat here for 20 mins trying to figure out why in my project the notifications were not showing, then realized I didn't change the class name in my config that overrides it and show it. Once I did that they showed :) Thats what I get for doing it at 12.15AM. Its now bed time!!

**Comment by markguinn** [comment]
Brilliant! Thanks for your work on this.

**Pull request merged**
